print("Wake up at 7:00 AM and stretch for 5 minutes.")
print("Brush teeth, wash face, and get dressed.")
print("Have breakfast with coffee and fruit.")
print("Check email and plan the day's tasks.")
print("Work on the most important project until lunch.")
print("Take a short walk or stretch break at 1:00 PM.")
print("Finish remaining work, review progress, and set goals for tomorrow.")
print("Cook dinner, relax with a book, and unwind.")
print("Prepare for bed and sleep by 10:30 PM.")